#' Prepare data input file
#'
#' Function to prepare data input file. The input data file can easily be prepared in excel or other programs. The function below may help the user in checking the right input format. Function only for the general data file, 'varves' and 'proxy' input data have to be formated separately.
#'
#' @export
#' @param which_lakes Name of the sites to be plotted. Must match folders names. Default: all the folder in the Cores folder.
#' @param output_name Extension to be added to the output name.
#' @keywords age-depth modelling
#' @keywords visualisation
#' @examples serac_input_formatting('PB06')
#'

serac_map <- function(which_lakes=c(), output_name=c())
  .serac_map(which_lakes,output_name)
.serac_map <- function(which_lakes,output_name) {
  # First, download packages
  pkgTest("ggmap")
  pkgTest("maptools")
  pkgTest("maps")

  # which lakes - either a selection, or all the folder in the Cores subfolder
  if(!is.null(which_lakes)) which_lakes=which_lakes else which_lakes <- list.dirs(path = "./Cores", full.names = FALSE, recursive = TRUE)

  # Go and read in every core_metadata files the coordinates
  stop_map = FALSE
  system_y = NULL
  system_x = NULL
  while(stop_map==FALSE) {
    for (i in 1:length(which_lakes)) {
      mylake <- which_lakes[i]
      if (!is.na(mylake)) {
        if(length(list.files(paste(getwd(),"/Cores/",mylake,"/", sep=""), pattern="serac_metadata_suppmetadata*", full.names=TRUE))!=1) {
          cat(paste("\n We did not find the supplementary data file for ",mylake,".\n This file is automatically generated in the function serac() if you keep\n the argument archive_metadata to TRUE the first time you run the code.\n\n", sep=""))
        } else {
          mdt <- read.csv(list.files(paste(getwd(),"/Cores/",mylake,"/", sep=""), pattern="serac_metadata_suppmetadata*", full.names=TRUE), header=T, sep="")
          if (length(grep("coordinates_y",mdt[,1])==1) && !is.na(mdt[grep("coordinates_y",mdt[,1]),2]) && length(grep("coordinates_x",mdt[,1])==1) && !is.na(mdt[grep("coordinates_x",mdt[,1]),2])) {
            system_y <- c(system_y,as.numeric(paste(mdt[grep("coordinates_y",mdt[,1]),2])))
            system_x <- c(system_x,as.numeric(paste(mdt[grep("coordinates_x",mdt[,1]),2])))
          } else {
            cat(paste("\n The format of coordinates for ",mylake," couldn't be read.\n Please check the input format you chose when you ran serac for your core.\n You can do that by running your code again and turning the argument \n archive_metadata to TRUE, or by accessing the 'serac_metadata_suppmetadata'\n file in your core folder. \n\n\n", sep=""))
          }
        }
      }
      if (i==length(which_lakes)) stop_map = TRUE
    }
  }
  # Using GGPLOT, plot the Base World Map
  par(mfrow=c(1,1))
  mp <- NULL
  mapWorld <- borders("world", colour="gray50", fill="gray50") # create a layer of borders
  mp <- ggplot() +   mapWorld

  # Now Layer the coring locations on top
  mp <- mp+ geom_point(aes(x=system_x, y=system_y) ,color="darkred", size=1)

  # Save the output
  if (is.null(output_name)) output_name <- "" else output_name <- paste("_",output_name, sep="")
  mp
  ggsave(paste("cores_location",output_name,".pdf",sep=""), plot = last_plot(), path = paste(getwd(),"/Cores/",sep=""), device="pdf")
}
