#' Map the sites
#'
#' Function to map the different sites an user worked on.
#'
#' @export
#' @param which_lakes Name of the sites to be plotted. Must match folders names. Default: all the folder in the Cores folder.
#' @param output_name Extension to be added to the output name.
#' @keywords age-depth modelling
#' @keywords visualisation
#' @examples serac_input_formatting('PB06')
#'

serac_map <- function(which_lakes=c(), output_name=c())
  .serac_map(which_lakes,output_name)
.serac_map <- function(which_lakes,output_name) {
  # First, download packages
  #pkgTest("ggmap")
  #pkgTest("maptools")
  #pkgTest("maps")
  pkgTest("ggplot2") # base ggplot2
  pkgTest("ggspatial")
  pkgTest("raster") # for function crs()
  pkgTest("sf")
  pkgTest("rnaturalearth") # base layer
  #pkgTest("rnaturalearthdata")

  # which lakes - either a selection, or all the folder in the Cores subfolder
  if(!is.null(which_lakes)) which_lakes=which_lakes else which_lakes <- list.dirs(path = "./Cores", full.names = FALSE, recursive = TRUE)

  # Go and read in every core_metadata files the coordinates
  stop_map = FALSE
  system_y = NULL
  system_x = NULL
  while(stop_map==FALSE) {
    for (i in 1:length(which_lakes)) {
      mylake <- which_lakes[i]
      if (!is.na(mylake)) {
        if(length(list.files(paste(getwd(),"/Cores/",mylake,"/", sep=""), pattern="serac_metadata_suppmetadata*", full.names=TRUE))!=1) {
          cat(paste("\n We did not find the supplementary data file for ",mylake,".\n This file is automatically generated in the function serac() if you keep\n the argument archive_metadata to TRUE the first time you run the code.\n\n", sep=""))
        } else {
          mdt <- read.csv(list.files(paste(getwd(),"/Cores/",mylake,"/", sep=""), pattern="serac_metadata_suppmetadata*", full.names=TRUE), header=T, sep="")
          if (length(grep("coordinates_y",mdt[,1])==1) && !is.na(mdt[grep("coordinates_y",mdt[,1]),2]) && length(grep("coordinates_x",mdt[,1])==1) && !is.na(mdt[grep("coordinates_x",mdt[,1]),2])) {
            system_y <- c(system_y,as.numeric(paste(mdt[grep("coordinates_y",mdt[,1]),2])))
            system_x <- c(system_x,as.numeric(paste(mdt[grep("coordinates_x",mdt[,1]),2])))
          } else {
            cat(paste("\n The format of coordinates for ",mylake," couldn't be read.\n Please check the input format you chose when you ran serac for your core.\n You can do that by running your code again and turning the argument \n archive_metadata to TRUE, or by accessing the 'serac_metadata_suppmetadata'\n file in your core folder. \n\n\n", sep=""))
          }
        }
      }
      if (i==length(which_lakes)) stop_map = TRUE
    }
  }

  # Read base layer
  world <- ne_coastline(scale = "small", returnclass = "sf")

  # Transform coordinates to the same CRS than base layer
  my_coord <- data.frame("lon" = as.numeric(paste(system_x)),
                         "lat" = as.numeric(paste(system_y)))
  my_coord <- my_coord[complete.cases(my_coord),]
  coordinates(my_coord)<-~lon+lat
  proj4string(my_coord)<-CRS("+proj=longlat +datum=WGS84")
  my_coord<-spTransform(my_coord,crs(world))

  # Using GGPLOT, plot the Base World Map
  mapWorld <- ggplot(data = world) +
    geom_sf(color = "black", fill = "lightgreen")  +
    annotation_scale(location = "bl", width_hint = 0.5) +
    annotation_north_arrow(location = "bl", which_north = "true",
                           pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                           style = north_arrow_fancy_orienteering) +
    xlab("Longitude") + ylab("Latitude")

  # Now Layer the coring locations on top
  mp <- mapWorld + geom_point(aes(x=my_coord$lon, y=my_coord$lat) ,color="orange", size=1, alpha=0.05)

  # Save the output
  if (is.null(output_name)) output_name <- "" else output_name <- paste("_",output_name, sep="")
  mp
  ggsave(paste("cores_location",output_name,".pdf",sep=""), plot = last_plot(), path = paste(getwd(),"/Cores/",sep=""), device="pdf")
}
